# name: Run cpptest

# on:
#   pull_request: #なんのとき
#     branches: ["main"]
#     #複数の場合["main","staging","dev"]

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4.2.2

#       - name: Install build dependencies
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y build-essential

#       - name: Compile 
#         run: make

#       - name: Run test
#         run: ./webserv 