servers:
  - server:
      listens:
        - listen:
            interface: 0.0.0.0
            port: 8080
        - listen:
            interface: 127.0.0.1
            port: 3000

      maxRequestBodySize: 1048576
      maxEvents: 1024
      timeoutSec: 60
      requestHeaderTimeoutSec: 15
      requestBodyTimeoutSec: 30

      access_logs:
        - access_log:
            sink: file
            filename: access.log
            logDir: ./logs
            format: ELF
            maxSize: 100KB
            maxBackup: 5
        - access_log:
            sink : console
            format : ELF

      error_logs:
        - error_log:
            sink: file
            filename: debug.log
            logDir: ./logs
            format: ELF
            level: debug
            mode: GREATER_OR_EQUAL
            maxSize: 1MB
            maxBackup: 3
        - error_log:
            sink: file
            filename: error.log
            logDir: ./logs
            format: ELF
            level: warning
        - error_log:
            sink : console
            level : debug

      interpreterPath:
        .php: /usr/bin/php-cgi
        .py: /usr/bin/python3

      locations:
        # Default location, allows most things, autoindex on
        - location:
            path: /
            root: ./www
            uploadStore: ./uploads
            indexFile: index.html
            autoindex: false
            session: true
            allowedMethods:
              - GET
              - HEAD
              - POST
              - DELETE

        - location:
            path: /cgi-bin
            root: ./www/cgi-bin/
            autoindex: false
            session: true
            interpreterPath:
              .php: /usr/bin/php-cgi
              .py: /usr/bin/python3
            allowedMethods:
              - GET
              - POST

        # Location for testing uploads and deletes specifically
        - location:
            path: /upload
            root: ./www/uploads
            uploadStore: ./uploads
            allowedMethods:
              - POST
              - DELETE

        # Location for testing 405 Method Not Allowed
        - location:
            path: /get_only
            root: ./www/
            allowedMethods:
              - GET

        # Location for testing 403 on a directory with autoindex off
        - location:
            path: /no_autoindex
            root: ./www/no_autoindex_dir
            autoindex: false
            allowedMethods:
              - GET

        # Location for testing 403 on a file with no permissions
        - location:
            path: /forbidden
            root: ./www/no_perms_default
            allowedMethods:
              - GET
