servers:
  - server:
      listens:
        - listen:
            interface: 0.0.0.0
            port: 8080
      maxEvents: 1024

      error_logs:
        - error_log:
            sink: file
            filename: debug.log
            level: Debug
        - error_log:
            sink: file
        - error_log:
            sink: console
            level: debug
