[pytest]
minversion = 6.0
addopts = -ra -q --cov=.. --cov-report=term-missing
testpaths =
    tests
    stress
    protocol
markers =
    core: サーバーの起動と設定パースのテスト
    http: 基本的なHTTPメソッドとレスポンスのテスト
    cgi: CGI機能のテスト
    upload: ファイルアップロードのテスト
    stress: 負荷・ノンブロッキングのテスト
    protocol: 低レベルなプロトコル堅牢性テスト
	integration: 統合テスト
