#!/usr/bin/env python3
# Simple Python CGI script for testing

import os
from datetime import datetime

# CGI Response Headers
print("Content-Type: text/html")
print("")  # Empty line separates headers from body

# HTML Response
print("<!DOCTYPE html>")
print("<html>")
print("<head><title>Python CGI Test</title></head>")
print("<body>")
print("<h1>Python CGI Script</h1>")
print("<p>This page is generated by a Python CGI script.</p>")
print("<h2>Environment Variables:</h2>")
print("<ul>")

# Display some CGI environment variables
cgi_vars = [
    'HTTP_COOKIE',
    'SERVER_SOFTWARE',
    'SERVER_NAME',
    'GATEWAY_INTERFACE',
    'SERVER_PROTOCOL',
    'SERVER_PORT',
    'REQUEST_METHOD',
    'PATH_INFO',
    'SCRIPT_NAME',
    'QUERY_STRING',
    'REMOTE_ADDR',
    'CONTENT_TYPE',
    'CONTENT_LENGTH',
    'HTTP_USER_AGENT',
    'HTTP_ACCEPT',
]

for var in cgi_vars:
    value = os.environ.get(var, '(not set)')
    print(f"<li><strong>{var}:</strong> {value}</li>")

print("</ul>")
print(f"<p><em>Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</em></p>")
print("</body>")
print("</html>")
